apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 postgres.default.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: chatbot
          image: sharagon1/chatbot:latest
          ports:
          - containerPort: 5000
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: chatbot-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: chatbot-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chatbot-secrets
                key: POSTGRES_PASSWORD
